name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: 'Node.js 18'
            os: ubuntu-latest
            nodejs: '18'
          - name: 'Node.js 19'
            os: ubuntu-latest
            nodejs: '19'
          - name: 'Windows'
            os: windows-latest
            nodejs: '19'

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Get the npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: npm-${{ hashFiles('./package.json') }}
          restore-keys: |
            npm-

      - name: Install npm dependencies
        run: |
          npm install
        shell: bash

      - name: Run the tests
        run: |
          npm run test
        shell: bash
